spring:
  application:
    name: config-client
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
#    means if that server is down or not running, it will default to application configurations (application.yml, application-prod/dev.yml)

build:
  id: ${BUILD_ID}
  version: ${BUILD_VERSION}
  name: ${BUILD_NAME}
  type: ${BUILD_TYPE}

management:
  endpoints:
    web:
      exposure:
        include: refresh
