spring:
  application:
    name: configclient
  config:
    import: optional:configserver:http://localhost:8888

build:
  id: 420
  version: 4.2.0
  name: native aah default in config-client app.yml
  type: native aah default in config-client app.yml

management:
  endpoints:
    web:
      exposure:
        include: refresh
